dist: trusty
sudo: required
services:
- docker
language: java
jdk: oraclejdk8
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: LdX7+gdraFrk9abxNZcZsqqXZBJkzr2mH+tEyvbaoevGOrl2Yi0rWQTbt2ghGWimGqLhYQ4nGa2tO3eOUs3j3PKRQwEdbGqqfoe3hInh6/TyT6XnBvFFI1G2aXo3A/HBuwo9hRLo9wcISsXBS5h0HmF4XgDpAbx2Bv8ukWmaYdd2SAG91myTou3XNecGdCq/Rxwh8x8WGa+hFLpqW5VqCAgm4OiPiFKYDVeQi4kpH22fTt0RhxFJ6LIoKQ4TDapiei9f+gZc772bLoGbC6+wjm9GdeVOr3Mxs9L85LsqL7G//2SOjItlexSWmwk/d67/Ko7j1gKoKVpQF1d2BvtAiVhLRMrQtt0v4Ykw/CQDc8Pt2b+Rl+sfy+OAR+lZdP8deKVkhM+f2N7RfVqeAXCH19+Imtu4pmVzrk5qUc8Fpszqce2N5DrWdj3ngmolWiGt3Eey0r58Z32asw4NeSblUuu67sU0pGPj10vruVyTUfo+nK6LVZt5gKweaTmiS3C74x33gFt803iu0BgsB1qTuSxJySjuvaCu+LTv5MByxNsjkqTdyYF1lMmXMQqUFf/iaxafcLuF+FrZV5esEAS8wu6rHAXkOkHlIAs6enbS+asFphEWXPgZn2mnrRyWaECVacJjlxpju+LSqNCSjOwDS+nkrSXch9e+SnxPEUPJ2jk=
  - secure: Kno9njbpbBVu6DaqibxYhI3SYGdhF68UlwOVz+KvGaEtxlk6J/+DPK0KhOBjQZCfMfVh/o3edCjO4fhLxMwUZuPOTBZo9yjrvqqlEBwmVfu+7ovfPIpPFkoDlqQwpeJ7ZePWeNq52NWPDTkzQqcPsiitA77WUFsuQ4nUClFmVMwxTRsraeFGkRlWy4uNuMFlS7xAUAZX35f/hz0fMf8VxqCXG5/FpU+jr1NKfQqMxIauXuj7/qd2DCrd2EQsrTKfivysGOzFBiWTI6eyhxCD1ttpD0c9WPnw2Fs4GlPE6HOcsuopcy2cQwSnNJhYA5B0G8UTLamP0RHJJkpx3Pz14nrZOWTakds5K9XvkKiXGKV4I9v/6OifOJCWsGE2AFpViUcW7fWVwpeEfgt3CFyRjelFKEe5SqpBmo3jyrwiog96nS5sRIH43BlreuARWEYWTxIOLGEuvVMKX8nLDKJCOo92KukEeDYYNgh9uDb6hj+LjA6QcfgX+hHRZ/pgg1t2RwBZ7IK861UMwyt+HWDvOnhEv5poQ7iDeTlNoGO9xar4Txp6z8FhiHrR17vDo6QJFxrb4yk0HOrc7b+xomsJkO7y071rBl+69tA+lvjkkzY7ibiQCu/xVSlAxTCH3F7jmP540nippHGuZT/L04wJGavwzmM1S15mc7QZKBp7eYg=
  - secure: cnzR7CqNegfxablxfEMtzudCRUDAqCbp2/r7b7zsbikhzE7Kl0lQCaBEOKaL8djnKsQrro6i17Gik/ovSEqStdRCLbKEpHt2rqOZFDJLeLns4eWhgMUSUbfPSht7r8/4+vL//lzsh3GcHr5F7aeRHnmXmQZduhM1usmRSDZODeuRp6iSMn3F3pX38NSXUM6MNxrcr/kI+MXG8HstoRdyAZnW8kdqdqygAttdB0J4u1x1jHMDcC2ZUC9aIMYs67b6Ru43vgW6lO4jwHpOwCwu2K70k5i8OO7oraVW6YBXq0aC/QzwcUYn+ulZVn9gNZsRFgTd1GbNnaewwuEWJs7DQ3NOQzUb3cKUpw3s9kLLhKnrvDqoC0YJvoau3gsKmzWLhfw3FMoS0CRIzoM68ge7BDfjWr48oem4QUm8Wcwsb4x50C4BA1I8Z0iDvG4k4JEcUshYvRcb4+3syG4Q5QFw5OerflpVIqFZBvYVBWiQX+VlJzCGcyrd65oemh3OiTFgURlSs7HZBG+3xl6VnS2iIoF+Arb8Gr/G8q34MD2hycA64aQdOh79KyJnX0h0HXsv0oxfjM5sQsTzFne6vZsmZRrqHyX6/9WYz9LA2XDhTqWjgoRm1O2vnLQEHXOe3awULRr5/s0XxHnGFJWRO2rIy3UT1j+vdXmTRuFSxOUhUvI=
script:
- echo "skipping tests"
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export CLOUD=ericlixj82/coinexchangeservice-cloud
- docker build -t $CLOUD:$COMMIT ./CLOUD
- docker tag $CLOUD:$COMMIT $CLOUD:$TAG
- docker push $CLOUD
